import type { Exercise } from '../../../api/fitness';
import type { MotionDefinition } from './types';
import { LatPulldown } from './LatPulldown';
import { cyclePose, circlePose, gaitPose, holdPose } from './timelines';
import {
  LegPress,
  ChestPress,
  SeatedRow,
  LegCurl,
  HipThrust,
  HipAbduction,
} from './MachineMotions';
import {
  DeadBug,
  Plank,
  TreadmillWalk,
  InclineWalk,
  FlatWalk,
  ShoulderCircles,
  HipCircles,
  Squat,
  CalfRaise,
  HipHinge,
} from './BodyMotions';
import {
  QuadStretch,
  HamstringStretch,
  CalfStretch,
  GluteStretch,
  ChestStretch,
  BackStretch,
} from './StretchMotions';

export const motions = {
  'lat-pulldown': {
    id: 'lat-pulldown',
    duration: 6,
    phaseLabels: ['起始姿势', '下拉过程', '短暂停留', '控制回位'],
    endLabel: '下拉结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['高位下拉', '高位下拉 Lat Pulldown', 'Lat Pulldown'],
    sourceLabel: 'NASM 高位下拉教学',
    Illustration: LatPulldown,
    poseAt: cyclePose,
    name: '高位下拉',
    subtitle: '胸前下拉 · 正握 · 动作示意',
    steps: [
      {
        name: '起始姿势',
        text: '坐稳，双脚踩地，大腿固定在压垫下。正握横杆，手臂向上伸展，胸部保持抬起。',
      },
      {
        name: '下拉与停留',
        text: '肩膀远离耳朵，肘部向下靠近身体两侧，横杆拉向上胸，短暂停留。躯干保持稳定。',
      },
      {
        name: '控制回位',
        text: '缓慢伸展手臂，让横杆回到头顶上方。保持拉索张紧，不让配重突然落下。',
      },
    ],
    errors: [
      '不要拉到颈后或低头迎杆。',
      '避免大幅后仰、摆动借力和持续耸肩。',
      '不要突然松手或让配重撞击。',
    ],
    source:
      'https://www.nasm.org/resource-center/blog/training/the-biomechanics-of-the-lat-pulldown-muscles-grip-and-form',
  },
  'leg-press': {
    Illustration: LegPress,
    poseAt: cyclePose,
    id: 'leg-press',
    name: '腿举',
    subtitle: '斜轨踏板式示意 · 侧面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '推出踏板', '短暂停留', '控制收回'],
    endLabel: '推出结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['腿举', '腿举 Leg Press', 'Leg Press'],
    steps: [
      { name: '起始姿势', text: '背部与头部靠稳，双脚放在踏板上，膝盖自然弯曲。' },
      { name: '动作过程', text: '脚掌稳定发力，推动踏板，逐渐伸展膝髋；膝保持微屈。' },
      { name: '回位与结束', text: '慢慢屈膝收回踏板，骨盆与背部保持贴靠。' },
    ],
    errors: ['不要锁死膝盖或让膝内扣。', '不要为了下得更深而抬起臀部。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/leg-press',
    sourceLabel: 'NASM 腿举教学',
  },
  'chest-press': {
    Illustration: ChestPress,
    poseAt: cyclePose,
    id: 'chest-press',
    name: '坐姿推胸',
    subtitle: '水平导轨式示意 · 侧面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '向前推', '短暂停留', '控制收回'],
    endLabel: '推出结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['坐姿推胸', '推胸', '坐姿推胸 Chest Press', 'Chest Press'],
    steps: [
      { name: '起始姿势', text: '坐稳靠背，脚踩地，把手调到胸部附近。' },
      { name: '动作过程', text: '双手推向前方，手腕保持自然，肘部逐渐伸展。' },
      { name: '回位与结束', text: '缓慢收回把手，背部继续贴靠，不让肩膀向前塌。' },
    ],
    errors: ['不要挺腰借力或抬起臀部。', '避免肘部锁死和手腕折弯。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/chest-press-machine',
    sourceLabel: 'NASM 坐姿推胸教学',
    note: '器械传动结构作简化处理；现场座椅与把手高度需按器械说明调整。',
  },
  'seated-row': {
    Illustration: SeatedRow,
    poseAt: cyclePose,
    id: 'seated-row',
    name: '坐姿划船',
    subtitle: '坐姿拉索式示意 · 侧面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '向后拉', '短暂停留', '控制回位'],
    endLabel: '拉回结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['坐姿划船', '划船', '坐姿划船 Seated Row', 'Seated Row'],
    steps: [
      { name: '起始姿势', text: '坐稳，脚抵住脚踏，手握手柄，胸部自然抬起。' },
      { name: '动作过程', text: '肘向后移动，将手柄拉向下胸与腹部附近，躯干保持稳定。' },
      { name: '回位与结束', text: '控制伸展手臂，让手柄回到前方，不甩身追随。' },
    ],
    errors: ['不要大幅前后摆动或耸肩。', '不要只用手腕拉动手柄。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/seated-machine-row-close-grip',
    sourceLabel: 'NASM 坐姿划船教学',
  },
  'leg-curl': {
    Illustration: LegCurl,
    poseAt: cyclePose,
    id: 'leg-curl',
    name: '坐姿腿弯举',
    subtitle: '固定膝轴与滚垫 · 侧面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '屈膝下卷', '短暂停留', '控制伸展'],
    endLabel: '弯举结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['坐姿腿弯举', '腿弯举', '坐姿腿弯举 Leg Curl', 'Leg Curl'],
    steps: [
      { name: '起始姿势', text: '坐稳靠背，膝关节对齐器械转轴，滚垫靠近脚踝，固定大腿。' },
      { name: '动作过程', text: '屈膝带动小腿向下向后卷，滚垫与小腿一起转动。' },
      { name: '回位与结束', text: '缓慢伸展膝盖回位，臀部继续贴靠座椅。' },
    ],
    errors: ['不要抬臀或甩腿借力。', '不要突然松开，让配重砸落。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/seated-leg-curl',
    sourceLabel: 'NASM 坐姿腿弯举教学',
    note: '传动位于器械内部，图中不虚构外露拉索。',
  },
  'hip-thrust': {
    Illustration: HipThrust,
    poseAt: cyclePose,
    id: 'hip-thrust',
    name: '臀推机',
    subtitle: '安全带式 Glute Drive 示意 · 侧面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '抬髋', '短暂停留', '控制下放'],
    endLabel: '抬髋结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['臀推', '臀推机', 'Hip Thrust', 'Glute Drive', '臀推机 Hip Thrust / Glute Drive'],
    steps: [
      { name: '起始姿势', text: '上背放在支撑垫上，髋部固定安全带，双脚踩稳踏板。' },
      { name: '动作过程', text: '脚掌发力抬髋，到肩、髋、膝接近一线的位置，短暂停留。' },
      { name: '回位与结束', text: '保持上背与脚的支撑，缓慢降低髋部和负重臂。' },
    ],
    errors: ['不要用腰部过度后弯来追求高度。', '不要让脚滑动或让安全带压在腹部。'],
    source: 'https://shop.lifefitness.com/products/hammer-strength-plate-loaded-glute-drive',
    sourceLabel: 'Life Fitness / Hammer Strength 器械说明',
    extraSources: [
      {
        label: 'NASM 髋伸展对齐参考',
        url: 'https://www.nasm.org/resource-center/blog/training/why-the-glute-bridge-belongs-in-almost-every-client-program',
      },
    ],
    note: '不同臀推机的支撑与锁定方式不同，使用前应核对现场说明；这不是杠铃臀推的器械示意。',
  },
  'hip-abduction': {
    Illustration: HipAbduction,
    poseAt: cyclePose,
    id: 'hip-abduction',
    name: '髋外展',
    subtitle: '外侧压垫与联动脚踏 · 正面视角',
    duration: 6,
    phaseLabels: ['起始姿势', '向外打开', '短暂停留', '控制收回'],
    endLabel: '打开结束',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['髋外展', '髋外展 Hip Abduction', 'Hip Abduction'],
    steps: [
      { name: '起始姿势', text: '坐稳靠背，大腿外侧抵住压垫，脚放在脚踏上。' },
      { name: '动作过程', text: '骨盆保持稳定，双腿向外打开，带动压垫和脚踏。' },
      { name: '回位与结束', text: '控制双腿向中间收回，不让压垫突然合拢。' },
    ],
    errors: ['不要晃动身体借力。', '确认压垫在外侧，不要混淆髋内收模式。'],
    source:
      'https://kb.cybexintl.com/Owners_Manuals/Strength/OM-OP_Life_Fitness_Axiom_Single_Station_Series_1014208-0001.pdf',
    sourceLabel: 'Life Fitness Axiom 使用手册',
    note: '正面图包含腿部投影的缩短；不是腿长改变。现场请核对器械外展模式。',
  },
  'dead-bug': {
    Illustration: DeadBug,
    poseAt: cyclePose,
    id: 'dead-bug',
    name: 'Dead Bug',
    subtitle: '对侧手脚交替 · 侧面视角',
    duration: 12,
    phaseLabels: ['起始姿势', '对侧伸展', '短暂停留', '收回换侧'],
    endLabel: '对侧伸展',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['Dead Bug', '死虫', '死虫式'],
    steps: [
      { name: '起始姿势', text: '仰卧，双手指向上方，髋膝弯曲，腰背稳定贴近垫面。' },
      { name: '动作过程', text: '缓慢伸出一侧手臂和对侧腿，保持腰背位置与自然呼吸。' },
      { name: '回位与结束', text: '收回手脚，再换另一组对侧手脚；只做能保持腰背稳定的幅度。' },
    ],
    errors: ['不要拱腰或憋气。', '不要为了伸得更远而失去腰背控制。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/dead-bug',
    sourceLabel: 'NASM Dead Bug教学',
  },
  plank: {
    Illustration: Plank,
    poseAt: holdPose,
    id: 'plank',
    name: '平板支撑',
    subtitle: '进入 → 保持 → 落膝 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备支撑', '抬膝进入', '稳定保持', '落膝退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['STRENGTH'],
    aliases: ['平板支撑', 'Plank'],
    steps: [
      { name: '起始姿势', text: '前臂撑地，肘位于肩下，膝盖先轻放垫面。' },
      { name: '动作过程', text: '抬膝，以前臂和脚尖支撑，头、躯干与腿保持稳定。' },
      { name: '回位与结束', text: '持续自然呼吸；结束时缓慢落膝，放松休息。' },
    ],
    errors: ['不要塌腰、撅臀或憋气。', '不要为了时间更长而丢失稳定姿势。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/plank',
    sourceLabel: 'NASM 平板支撑教学',
  },
  'treadmill-walk': {
    Illustration: TreadmillWalk,
    poseAt: gaitPose,
    id: 'treadmill-walk',
    name: '跑步机走路',
    subtitle: '平地跑带式示意 · 速度按原计划',
    duration: 2,
    phaseLabels: ['一侧落地', '支撑推进', '对侧迈步', '交替落地'],
    endLabel: '迈步姿势',
    stillSeconds: 0.9,
    types: ['CARDIO'],
    aliases: ['跑步机热身', '慢走冷身', '冷身', '跑步机走路', '长爬坡：热身', '长爬坡：冷身'],
    steps: [
      { name: '起始姿势', text: '站稳后开始小步行走，目视前方，肩颈放松。' },
      { name: '动作过程', text: '双腿交替落地与迈步，手臂对侧自然摆动。' },
      { name: '回位与结束', text: '热身与冷身逐渐调整节奏；跑步机先减速再离开。' },
    ],
    errors: ['不要跨大步或长时间抓住扶手悬挂身体。', '需要持续拉扶手时，降低速度或坡度。'],
    source:
      'https://www.acefitness.org/continuing-education/prosource/april-2016/5865/functional-anatomy-series-the-abdominals/',
    sourceLabel: 'ACE 对侧摆臂与步态参考',
    note: '步态为通用简化示意，不将动画节奏换算成你的速度、坡度或训练时长。',
  },
  'incline-walk': {
    Illustration: InclineWalk,
    poseAt: gaitPose,
    id: 'incline-walk',
    name: '跑步机爬坡',
    subtitle: '倾斜跑带式示意 · 图中坡度不代表计划数值',
    duration: 2,
    phaseLabels: ['一侧落地', '支撑推进', '对侧迈步', '交替落地'],
    endLabel: '迈步姿势',
    stillSeconds: 0.9,
    types: ['CARDIO'],
    aliases: [
      '跑步机爬坡',
      '坡走',
      '开始爬坡',
      '正式爬坡',
      '降坡',
      '长爬坡：升坡',
      '长爬坡：坡度5',
      '长爬坡：坡度6',
      '长爬坡：降至坡度5',
      '长爬坡：降坡',
    ],
    steps: [
      { name: '起始姿势', text: '站稳后开始小步行走，目视前方，肩颈放松。' },
      { name: '动作过程', text: '双腿交替落地与迈步，手臂对侧自然摆动。' },
      { name: '回位与结束', text: '热身与冷身逐渐调整节奏；跑步机先减速再离开。' },
    ],
    errors: ['不要跨大步或长时间抓住扶手悬挂身体。', '需要持续拉扶手时，降低速度或坡度。'],
    source:
      'https://www.acefitness.org/continuing-education/prosource/april-2016/5865/functional-anatomy-series-the-abdominals/',
    sourceLabel: 'ACE 对侧摆臂与步态参考',
    note: '步态为通用简化示意，不将动画节奏换算成你的速度、坡度或训练时长。',
  },
  'flat-walk': {
    Illustration: FlatWalk,
    poseAt: gaitPose,
    id: 'flat-walk',
    name: '平地走路',
    subtitle: '自然步态示意 · 速度按原计划',
    duration: 2,
    phaseLabels: ['一侧落地', '支撑推进', '对侧迈步', '交替落地'],
    endLabel: '迈步姿势',
    stillSeconds: 0.9,
    types: ['CARDIO'],
    aliases: ['平地快走热身', '平地快走', '慢走', '散步', '走路', '快走'],
    steps: [
      { name: '起始姿势', text: '站稳后开始小步行走，目视前方，肩颈放松。' },
      { name: '动作过程', text: '双腿交替落地与迈步，手臂对侧自然摆动。' },
      { name: '回位与结束', text: '热身与冷身逐渐调整节奏；跑步机先减速再离开。' },
    ],
    errors: ['不要跨大步或长时间抓住扶手悬挂身体。', '需要持续拉扶手时，降低速度或坡度。'],
    source:
      'https://www.acefitness.org/continuing-education/prosource/april-2016/5865/functional-anatomy-series-the-abdominals/',
    sourceLabel: 'ACE 对侧摆臂与步态参考',
    note: '步态为通用简化示意，不将动画节奏换算成你的速度、坡度或训练时长。',
  },
  'dynamic-warmup': {
    Illustration: ShoulderCircles,
    poseAt: circlePose,
    id: 'dynamic-warmup',
    name: '肩部前后绕环',
    subtitle: '动态热身 · 按原计划次数练习',
    duration: 8,
    phaseLabels: ['准备姿势', '向前绕环', '自然过渡', '向后绕环'],
    endLabel: '动作关键姿势',
    stillSeconds: 1,
    types: ['MOBILITY', 'STRENGTH'],
    aliases: ['动态热身', '肩部绕环', '肩绕环'],
    steps: [
      { name: '起始姿势', text: '自然站立，双臂放松垂下。' },
      { name: '动作过程', text: '肩部以舒适的小幅度缓慢绕环，先向前再向后。' },
      { name: '回位与结束', text: '完成后放松，按原计划的次数进行。' },
    ],
    errors: ['避免用力甩动、憋气或追求过大幅度。', '动作范围以平稳、舒适为限。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 动作与热身参考',
    related: ['dynamic-warmup', 'hip-circles', 'bodyweight-squat', 'calf-raise', 'hip-hinge'],
  },
  'hip-circles': {
    Illustration: HipCircles,
    poseAt: circlePose,
    id: 'hip-circles',
    name: '髋部绕环',
    subtitle: '动态热身 · 按原计划次数练习',
    duration: 8,
    phaseLabels: ['准备姿势', '绕环过程', '自然过渡', '绕环回位'],
    endLabel: '动作关键姿势',
    stillSeconds: 1,
    types: ['MOBILITY', 'STRENGTH'],
    aliases: ['髋部绕环', '髋绕环'],
    steps: [
      { name: '起始姿势', text: '双脚分开站稳，双手轻扶髋部。' },
      { name: '动作过程', text: '骨盆小幅绕圈，膝微屈，双脚保持在地面。' },
      { name: '回位与结束', text: '缓慢完成一圈后回到中立站姿，按原计划进行。' },
    ],
    errors: ['避免用力甩动、憋气或追求过大幅度。', '动作范围以平稳、舒适为限。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 动作与热身参考',
    related: ['dynamic-warmup', 'hip-circles', 'bodyweight-squat', 'calf-raise', 'hip-hinge'],
  },
  'bodyweight-squat': {
    Illustration: Squat,
    poseAt: cyclePose,
    id: 'bodyweight-squat',
    name: '徒手深蹲',
    subtitle: '动态热身 · 按原计划次数练习',
    duration: 6,
    phaseLabels: ['起始姿势', '下蹲', '短暂停留', '站起回位'],
    endLabel: '动作关键姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY', 'STRENGTH'],
    aliases: ['徒手深蹲', '深蹲'],
    steps: [
      { name: '起始姿势', text: '双脚站稳，胸部自然抬起，双手向前保持平衡。' },
      { name: '动作过程', text: '髋向后坐，膝髋一起弯曲，膝盖与脚尖同向。' },
      { name: '回位与结束', text: '脚掌发力站起，回到自然站姿。' },
    ],
    errors: ['避免用力甩动、憋气或追求过大幅度。', '动作范围以平稳、舒适为限。'],
    source: 'https://www.nasm.org/resource-center/exercise-library/prisoner-squat',
    sourceLabel: 'NASM 动作与热身参考',
    related: ['dynamic-warmup', 'hip-circles', 'bodyweight-squat', 'calf-raise', 'hip-hinge'],
    note: '手臂位置采用平衡站姿；参考深蹲的膝髋动作原则，不改变原计划。',
  },
  'calf-raise': {
    Illustration: CalfRaise,
    poseAt: cyclePose,
    id: 'calf-raise',
    name: '提踵',
    subtitle: '动态热身 · 按原计划次数练习',
    duration: 6,
    phaseLabels: ['起始姿势', '抬起脚跟', '短暂停留', '控制落跟'],
    endLabel: '动作关键姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY', 'STRENGTH'],
    aliases: ['提踵', '站姿提踵'],
    steps: [
      { name: '起始姿势', text: '站稳，双脚自然分开，可轻扶固定支撑。' },
      { name: '动作过程', text: '以前脚掌支撑，缓慢抬起脚跟，保持平衡。' },
      { name: '回位与结束', text: '控制脚跟落回地面，不弹跳。' },
    ],
    errors: ['避免用力甩动、憋气或追求过大幅度。', '动作范围以平稳、舒适为限。'],
    source:
      'https://www.nasm.org/resource-center/blog/training/calf-training-how-to-program-this-stubborn-muscle-group-for-clients',
    sourceLabel: 'NASM 动作与热身参考',
    related: ['dynamic-warmup', 'hip-circles', 'bodyweight-squat', 'calf-raise', 'hip-hinge'],
  },
  'hip-hinge': {
    Illustration: HipHinge,
    poseAt: cyclePose,
    id: 'hip-hinge',
    name: '髋铰链',
    subtitle: '动态热身 · 按原计划次数练习',
    duration: 6,
    phaseLabels: ['起始姿势', '髋向后推', '短暂停留', '站直回位'],
    endLabel: '动作关键姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY', 'STRENGTH'],
    aliases: ['髋铰链', 'Hip Hinge'],
    steps: [
      { name: '起始姿势', text: '双脚站稳，膝盖微屈，保持背部自然。' },
      { name: '动作过程', text: '髋向后推，躯干从髋部整体前倾。' },
      { name: '回位与结束', text: '收紧臀部站直，回到中立位置。' },
    ],
    errors: ['避免用力甩动、憋气或追求过大幅度。', '动作范围以平稳、舒适为限。'],
    source: 'https://www.acefitness.org/resources/everyone/exercise-library/33/hip-hinge/',
    sourceLabel: 'ACE 髋铰链教学',
    related: ['dynamic-warmup', 'hip-circles', 'bodyweight-squat', 'calf-raise', 'hip-hinge'],
  },
  'recovery-stretch': {
    Illustration: QuadStretch,
    poseAt: holdPose,
    id: 'recovery-stretch',
    name: '大腿前侧拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['恢复拉伸', '大腿前侧拉伸'],
    steps: [
      { name: '起始姿势', text: '扶稳固定支撑，身体自然站直。' },
      { name: '动作过程', text: '一侧屈膝，轻扶脚踝，脚跟靠近臀部，双膝靠近。' },
      { name: '回位与结束', text: '保持轻度牵拉后缓慢松手，换侧；按原计划每侧20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.worcsacute.nhs.uk/leaflets/stretching-exercises-physiotherapy/',
    sourceLabel: 'NHS 站姿大腿拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
  'hamstring-stretch': {
    Illustration: HamstringStretch,
    poseAt: holdPose,
    id: 'hamstring-stretch',
    name: '大腿后侧拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['大腿后侧拉伸'],
    steps: [
      { name: '起始姿势', text: '坐在垫上，腿向前伸，膝可微屈。' },
      { name: '动作过程', text: '从髋部轻向前倾，背部保持自然延伸。' },
      { name: '回位与结束', text: '保持轻度牵拉后缓慢回正；按原计划20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 初学者拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
  'calf-stretch': {
    Illustration: CalfStretch,
    poseAt: holdPose,
    id: 'calf-stretch',
    name: '小腿拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['小腿拉伸'],
    steps: [
      { name: '起始姿势', text: '扶墙前后站立，双脚朝向前方。' },
      { name: '动作过程', text: '轻向前移重心，后脚跟保持踩地。' },
      { name: '回位与结束', text: '保持轻度牵拉后回正、换侧；按原计划每侧20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 初学者拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
  'glute-stretch': {
    Illustration: GluteStretch,
    poseAt: holdPose,
    id: 'glute-stretch',
    name: '臀部拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['臀部拉伸'],
    steps: [
      { name: '起始姿势', text: '仰卧，一侧脚踝搭在另一侧大腿上。' },
      { name: '动作过程', text: '轻带支撑腿靠近胸部，保持头背放松。' },
      { name: '回位与结束', text: '保持后松开、换侧；按原计划每侧20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 初学者拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
  'chest-stretch': {
    Illustration: ChestStretch,
    poseAt: holdPose,
    id: 'chest-stretch',
    name: '胸部拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['胸部拉伸', '胸拉伸'],
    steps: [
      { name: '起始姿势', text: '站在门框旁，一侧前臂轻扶门框。' },
      { name: '动作过程', text: '身体轻远离支撑侧，胸部自然打开。' },
      { name: '回位与结束', text: '保持轻度牵拉后缓慢回正、换侧；按原计划每侧20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 初学者拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
  'back-stretch': {
    Illustration: BackStretch,
    poseAt: holdPose,
    id: 'back-stretch',
    name: '背部拉伸',
    subtitle: '进入 → 保持 → 退出 · 示意时长不代替训练计时',
    duration: 12,
    phaseLabels: ['准备姿势', '缓慢进入', '轻度保持', '缓慢退出'],
    endLabel: '保持姿势',
    stillSeconds: 2.5,
    types: ['MOBILITY'],
    aliases: ['背部拉伸', '背拉伸'],
    steps: [
      { name: '起始姿势', text: '跪在垫上，双手轻放前方。' },
      { name: '动作过程', text: '髋向脚跟坐，手向前伸，躯干缓慢降低。' },
      { name: '回位与结束', text: '自然呼吸，保持后缓慢起身；按原计划20～30秒。' },
    ],
    errors: ['不要在拉伸中弹动或强拉。', '不憋气，出现疼痛时停止。'],
    source: 'https://www.nasm.org/resource-center/blog/recovery/stretches-for-beginners',
    sourceLabel: 'NASM 初学者拉伸参考',
    related: [
      'recovery-stretch',
      'hamstring-stretch',
      'calf-stretch',
      'glute-stretch',
      'chest-stretch',
      'back-stretch',
    ],
    note: '画面只示意一侧。实际按原计划完成保持与换侧；不是自动训练计时器。',
  },
} as const satisfies Record<string, MotionDefinition>;
export type MotionId = keyof typeof motions;
const recordBindings: Readonly<Record<string, MotionId>> = {};
const aliases = new Map<string, MotionId>();
const normalize = (value: string) => value.trim().replace(/\s+/g, ' ').toLowerCase();
for (const [id, motion] of Object.entries(motions)) {
  for (const alias of motion.aliases) aliases.set(normalize(alias), id as MotionId);
}
export function resolveMotion(
  exercise: Pick<Exercise, 'id' | 'name' | 'type'>,
): MotionId | undefined {
  const id =
    recordBindings[exercise.id] ??
    (Object.hasOwn(motions, exercise.id)
      ? (exercise.id as MotionId)
      : aliases.get(normalize(exercise.name)));
  if (!id) return undefined;
  const motion: MotionDefinition = motions[id];
  return motion.types.includes(exercise.type) ? id : undefined;
}
