import { apiRequest } from './http';
export type Level = 'simple' | 'middle' | 'hard';
export interface LevelProgress { available: number; target: number; completed: number; correct: number; passed: boolean; currentRate: number; rateLabel?: '正确率' | '得分率'; earned?: number; maximum?: number }
export interface BankPoint { point_key: string; chapter_id: string; title: string; scope_verified: boolean; legacy_ids: string[]; scope_evidence: string; levels: Record<Level, LevelProgress> }
export interface BankChapter { chapter_id: string; title: string; required: boolean; points: BankPoint[]; simpleMissing: number; middleMissing: number; middleUnlocked: boolean; hardUnlocked: boolean; chapterAssessmentUnlocked: boolean; passed: boolean; blockReasons: string[] }
export interface BankVersion { id: string; course_id: string; state: string; version_no: number; revision: number }
export interface BankPaper { id: string; title: string; chapter_id: string | null; kind: 'CHAPTER' | 'MOCK'; variant: string; limit_minutes: number; structure_evidence?: string; revision?: number; reviewed?: boolean }
export interface BankOverview { version: BankVersion; published: boolean; completePublished?: boolean; practicePublishedCount?: number; chapters: BankChapter[]; papers: BankPaper[]; canApplyMock: boolean; missingChapterIds: string[]; mockBlockReasons: string[]; canReadPapers: boolean; examBlockReasons: string[]; unlockSources: string[]; qualifications: Record<string, unknown>[]; legacyQualifications: Record<string, unknown>[] }
export interface BankQuestion { id: string; point_key: string; type: string; stem: string; options: string[]; maximum: number; level: Level; explanation?: string; solution?: Record<string, unknown>; review_state?: string; revision?: number; coverage_form?: string; source_evidence?: string; difficulty_basis?: string; auxiliary_points?: string[]; legacy_revision_id?: string; retirement_reason?: string; recheck_evidence?: string; solve_evidence?: string; review_agent?: string; practice_published_at?: string; retired_at?: string; rubric?: Record<string, unknown>[]; saved?: { answer: { selectedOption?: number; text?: string } | null; grading_state: string; earned: number | null; revision: number; feedback: string | null } }
export interface BankSession { id: string; status: string; kind: string; variant: string; revision: number; questions: BankQuestion[]; earned: number | null; maximum: number; passed: boolean; timed_out: boolean; answers_previously_revealed: boolean; rate: number | null; rateLabel: string; deadline_at: string; serverTime: string; complete: boolean }
export interface BankAttempt { id: string; questionId: string; gradingState: string; earned: number | null; maximum: number; correct: boolean | null; solution?: Record<string, unknown>; explanation?: string }
export interface BankValidation { valid: boolean; errors: string[]; gaps: { pointKey: string; pointTitle: string; chapterId: string; level: Level; verified: number; target: number; gap: number }[]; pendingLegacyReviews: number; verifiedQuestionCount: number }
export interface BankAdmin { version: BankVersion; chapters: BankChapter[]; points: BankPoint[]; validation: BankValidation; papers: BankPaper[]; qualifications: Record<string, unknown>[]; legacyReplacementComplete?: boolean; practicePublishedCount?: number; practiceBatches?: { batch_key: string; question_count: number; published_at: string; review_evidence: string }[] }
export interface BankReview { legacy_revision_id: string; decision: string; reasons: string[]; original_snapshot: { stem: string; options: string[]; correctOption: number; explanation: string; difficulty: number; sourceLocator: string; questionId: string; chapterId: string }; proposed_question_id: string | null; revision: number }
export interface GradeItem { target_id: string; question_id: string; kind: 'PRACTICE' | 'SESSION'; stem: string; type: string; maximum: number; grading_state: string; answer: unknown; solution: unknown; rubric: unknown; revision: number }
export async function bankRequest<T>(path: string, method = 'GET', data?: unknown, key?: string): Promise<T> {
  return (await apiRequest<{ data: T }>({ url: `/api/v1${path}`, method, data, silent: true, headers: key ? { 'Idempotency-Key': key } : {} })).data;
}
