import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { bankRequest, type BankAdmin as AdminData, type BankReview, type BankQuestion, type BankPaper, type GradeItem } from '../../api/bank';
import { Button } from '../../components/Button';
import { MathText } from '../../components/MathText';
import './bank.css';
const decisions: Record<string, string> = { KEEP: '保留', REVISE: '修订', RETIRE: '不通过（删除）', PENDING: '待核实' };
export function BankAdmin({ courseId }: { courseId: string }) {
  const client = useQueryClient();const [tab, setTab] = useState('reviews');const [page, setPage] = useState(1);const [filter, setFilter] = useState('PENDING');const [point, setPoint] = useState('');
  const [busy, setBusy] = useState(false);const [error, setError] = useState('');const [success, setSuccess] = useState('');
  const data = useQuery({ queryKey: ['admin-bank', courseId], enabled: !!courseId, queryFn: () => bankRequest<AdminData>(`/admin/bank/courses/${courseId}`) });
  const reviews = useQuery({ queryKey: ['admin-bank-reviews', courseId, filter, page], enabled: !!courseId && tab === 'reviews', queryFn: () => bankRequest<{ items: BankReview[]; total: number }>(`/admin/bank/courses/${courseId}/reviews?page=${page}&size=10${filter ? `&decision=${filter}` : ''}`) });
  const questions = useQuery({ queryKey: ['admin-bank-questions', courseId, point], enabled: !!courseId && tab === 'questions', queryFn: () => bankRequest<BankQuestion[]>(`/admin/bank/courses/${courseId}/questions?${new URLSearchParams({ ...(point ? { pointKey: point } : {}) })}`) });
  const grading = useQuery({ queryKey: ['admin-bank-grading', courseId], enabled: !!courseId && tab === 'grading', queryFn: () => bankRequest<GradeItem[]>(`/admin/bank/courses/${courseId}/grading`) });
  const cleanup = useQuery({ queryKey: ['admin-bank-deletions', courseId], enabled: !!courseId && tab === 'cleanup', queryFn: () => bankRequest<CleanupItem[]>(`/admin/bank/courses/${courseId}/deletions`) });
  async function act(fn: () => Promise<unknown>) { setBusy(true);setError('');setSuccess('');try {await fn();setSuccess('已保存，已重新读取后端状态。');await client.invalidateQueries({ predicate: (q) => String(q.queryKey[0]).startsWith('admin-bank') });} catch (e) {setError(e instanceof Error ? e.message : '操作失败');} finally {setBusy(false);} }
  if (data.isPending) return <p>正在读取题库审查工作台…</p>;
  if (data.isError) return <p role="alert">{data.error.message}<Button onClick={() => void data.refetch()}>重试</Button></p>;
  const info = data.data;const draft = info.version.state === 'DRAFT';
  return <div className="bank-admin"><header><h2>题库审查与发布</h2><p>最新题库 · {draft ? '审核中' : '已发布'} · 已复核题 {info.validation.verifiedQuestionCount} 道 · 旧题待核实 {info.validation.pendingLegacyReviews} 道 · 已分批发布练习 {info.practicePublishedCount ?? 0} 道</p>{info.legacyReplacementComplete && <p role="status">旧题及关联作答快照已整体移除，当前按考点重新编制原创题；尚未复核的草稿不计入合格题量。</p>}<p>每考点三个等级各10题；未重解、来源待核实、主观题缺评分标准或独立卷不足时不能发布。</p></header>
    <div className="row">{[['reviews', '逐题审查'], ['gaps', '范围与题量缺口'], ['questions', '题目草稿与复核'], ['papers', '固定试卷'], ['grading', '主观题评分'], ['cleanup', '不合格历史清理']].map(([key, title]) => <Button key={key} variant={tab === key ? 'primary' : 'secondary'} onClick={() => setTab(key)}>{title}</Button>)}</div>
    {error && <p role="alert">{error}</p>}{success && <p role="status">{success}</p>}
    {tab === 'reviews' && <><label>审查结论<select value={filter} onChange={(e) => {setFilter(e.target.value);setPage(1);}}><option value="">全部</option>{Object.entries(decisions).filter(([k]) => k !== 'RETIRE').map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>{reviews.isPending ? <p>读取中…</p> : reviews.isError ? <p role="alert">{reviews.error.message}</p> : <>{reviews.data.items.map((r) => <Review key={r.legacy_revision_id + ':' + r.revision} courseId={courseId} review={r} act={act} busy={busy} onRejected={() => setTab('cleanup')} />)}<div className="row"><Button disabled={page === 1 || busy} onClick={() => setPage(page - 1)}>上一页</Button><span>第 {page} 页 · 共 {reviews.data.total} 条</span><Button disabled={page * 10 >= reviews.data.total || busy} onClick={() => setPage(page + 1)}>下一页</Button></div></>}</>}
    {tab === 'gaps' && <><p>范围审核需记录具体大纲、教材版次、页码或可核查官方链接。用户确认考点口径不等于已核实考试范围。</p>{info.points.map((p) => <Scope key={p.point_key} courseId={courseId} data={info} point={p} act={act} busy={busy} />)}<table><thead><tr><th>考点</th><th>等级</th><th>已审核</th><th>缺口</th></tr></thead><tbody>{info.validation.gaps.filter((g) => g.verified !== 10).map((g) => <tr key={g.pointKey + g.level}><td>{g.pointTitle}</td><td>{g.level}</td><td>{g.verified}/10</td><td>{g.gap}</td></tr>)}</tbody></table></>}
    {tab === 'questions' && <><label>主考点<select aria-label="主考点" value={point} onChange={(e) => setPoint(e.target.value)}><option value="">请选择考点</option>{info.points.map((p) => <option key={p.point_key} value={p.point_key}>{p.title}</option>)}</select></label>{draft && point && <QuestionEditor key={point + ':' + info.version.revision} courseId={courseId} data={info} point={point} act={act} busy={busy} />}{questions.isPending ? <p>读取中…</p> : questions.isError ? <p role="alert">{questions.error.message}</p> : questions.data.map((q) => <details key={q.id + ':' + q.revision} className="bank-review"><summary>{q.type} · {q.level ?? '独立卷题'} · {q.review_state} · {q.coverage_form}</summary><MathText text={q.stem} /><p>来源：{q.source_evidence}</p><p>难度依据：{q.difficulty_basis}</p><p>发布：{q.practice_published_at ? "已开放练习" : "尚未开放"}</p>{q.solution && <><p>参考答案：</p><MathText text={q.type === "CHOICE" ? q.options[Number(q.solution.correctOption)] ?? "" : String(q.solution.referenceAnswer ?? "")} /></>}{!!q.rubric?.length && <ul>{q.rubric.map((r) => <li key={String(r.id)}>{String(r.description)}（{String(r.maximum)}分）</li>)}</ul>}{q.recheck_evidence && <p>复核依据：{q.recheck_evidence}</p>}<p>题目身份：{q.id}</p>{q.retirement_reason && <p>删除原因：{q.retirement_reason} · {q.retired_at}</p>}<MathText text={q.explanation ?? ''} />{draft && q.review_state !== 'VERIFIED' && q.review_state !== 'RETIRED' && <QuestionEditor courseId={courseId} data={info} point={q.point_key} question={q} act={act} busy={busy} />}{q.review_state !== 'RETIRED' && <Verification courseId={courseId} data={info} question={q} act={act} busy={busy} />}</details>)}</>}
    {tab === 'papers' && <><p>章节卷覆盖全章，模拟卷覆盖全科必考范围；只能选择独立卷题，不直接使用练习题。A/B/C必须有相同题型分值结构与时限，并记录难度复核依据。</p>{draft && <PaperEditor courseId={courseId} data={info} act={act} busy={busy} />}{info.papers.map((p) => <PaperReview key={p.id} courseId={courseId} data={info} paper={p} act={act} busy={busy} />)}</>}
    {tab === 'grading' && (grading.isPending ? <p>读取中…</p> : grading.isError ? <p role="alert">{grading.error.message}</p> : grading.data.length ? grading.data.map((g) => <Grade key={g.target_id + g.question_id + g.revision} item={g} act={act} busy={busy} />) : <p>暂无待评分或待核对作答。</p>)}
    {tab === 'cleanup' && <><p>这里只列出已明确判定不合格且还有历史引用的题目。删除范围由后端按题目身份计算，包含其作答、快照及含该题的整份旧检测记录与相关通过资格；其他题目的独立记录保留。</p>{cleanup.isPending ? <p>正在计算删除清单…</p> : cleanup.isError ? <p role="alert">{cleanup.error.message}</p> : cleanup.data.length ? cleanup.data.map((item, index) => <HistoryCleanup key={item.questionId} courseId={courseId} item={item} index={index + 1} act={act} busy={busy} />) : <p>没有待清理的不合格旧题记录。</p>}</>}
    {draft && <PracticeBatchPublisher courseId={courseId} data={info} act={act} busy={busy} />}
    {!!info.practiceBatches?.length && <details><summary>练习发布批次</summary>{info.practiceBatches.map((b) => <p key={b.batch_key}>{b.batch_key} · {b.question_count}道 · {b.published_at} · {b.review_evidence}</p>)}</details>}
    <details><summary>通过凭据与管理员作废（最近100条）</summary><p>作废考点练习凭据会同步作废本等级的章节汇总凭据；旧作答仍可读取，重新达标需在作废后完成全部不同题。</p>{info.qualifications.map((q) => <Qualification key={String(q.id)} item={q} act={act} busy={busy} />)}</details>
    <details><summary>发布校验 · {info.validation.valid ? '通过' : `${info.validation.errors.length} 项阻断`}</summary><ul>{info.validation.errors.map((e, i) => <li key={i}>{e}</li>)}</ul></details>
    {draft ? <Button loading={busy} disabled={!info.validation.valid} disabledReason="需补齐全部配额、全量审查、范围证据及独立试卷并复核" onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/versions/${info.version.id}/publish`, 'POST', { expectedRevision: info.version.revision }))}>发布经过完整复核的版本</Button> : <Button loading={busy} onClick={() => void act(async () => {await bankRequest(`/admin/bank/courses/${courseId}/drafts`, 'POST');setPoint('');})}>更新题库</Button>}
  </div>;
}
type Action = (fn: () => Promise<unknown>) => Promise<void>;
function Review({ courseId, review, act, busy, onRejected }: { courseId: string; review: BankReview; act: Action; busy: boolean; onRejected: () => void }) {
  const [decision, setDecision] = useState(review.decision);const [reasons, setReasons] = useState(review.reasons.join('\n'));const [replacement, setReplacement] = useState(review.proposed_question_id ?? '');
  const original = review.original_snapshot;
  const compared = useQuery({ queryKey: ['admin-bank-comparison', courseId, replacement], enabled: !!replacement, queryFn: () => bankRequest<BankQuestion>(`/admin/bank/courses/${courseId}/questions/${replacement}`) });
  return <article className="bank-review"><p>旧题 {original.questionId} · 原难度 {original.difficulty}（不自动映射等级）</p><MathText text={original.stem} />{original.options.map((o, i) => <p key={i}>{String.fromCharCode(65 + i)}. <MathText text={o} /></p>)}<p>原答案：{String.fromCharCode(65 + original.correctOption)} · 旧来源：{original.sourceLocator}</p><MathText text={original.explanation} />
    {compared.data && <section><h4>修订对照</h4><p>新题型：{compared.data.type} · 新等级：{compared.data.level}</p><MathText text={compared.data.stem} /><MathText text={compared.data.explanation ?? ''} /></section>}
    <label>结论<select aria-label="结论" value={decision} onChange={(e) => setDecision(e.target.value)}>{Object.entries(decisions).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>具体依据（每项一行）<textarea aria-label="具体依据（每项一行）" value={reasons} onChange={(e) => setReasons(e.target.value)} /></label><label>保留/修订后的新题身份<input value={replacement} onChange={(e) => setReplacement(e.target.value)} /></label><Button loading={busy} disabled={!reasons.trim()} onClick={() => void act(async () => {const result = await bankRequest<{ historyCleanupRequired?: boolean }>(`/admin/bank/courses/${courseId}/reviews/${review.legacy_revision_id}`, 'PUT', { decision, reasons: reasons.split('\n').filter((s) => s.trim()), proposedQuestionId: replacement || null, expectedRevision: review.revision });if (result.historyCleanupRequired) onRejected();})}>{decision === 'RETIRE' ? '判定不通过并删除' : '保存逐题结论'}</Button>
  </article>;
}
function Scope({ courseId, data, point, act, busy }: { courseId: string; data: AdminData; point: AdminData['points'][number]; act: Action; busy: boolean }) {
  const [evidence, setEvidence] = useState(point.scope_verified ? point.scope_evidence : '');
  return <details className="bank-review"><summary>{point.title} · {point.scope_verified ? '范围已核实' : '范围待核实'}</summary><p>原考点身份：{point.legacy_ids.join('、') || '按已确认手册口径新增'}</p><label>范围证据<textarea value={evidence} onChange={(e) => setEvidence(e.target.value)} /></label><Button loading={busy} disabled={!evidence.trim() || data.version.state !== 'DRAFT'} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/versions/${data.version.id}/scope?pointKey=${encodeURIComponent(point.point_key)}`, 'PUT', { evidence, expectedRevision: data.version.revision }))}>确认范围证据</Button></details>;
}
function QuestionEditor({ courseId, data, point, question, act, busy }: { courseId: string; data: AdminData; point: string; question?: BankQuestion; act: Action; busy: boolean }) {
  const [type, setType] = useState(question?.type ?? 'CHOICE');const [purpose, setPurpose] = useState(question?.level ? 'PRACTICE' : question ? 'ASSESSMENT' : 'PRACTICE');const [level, setLevel] = useState(question?.level ?? 'simple');
  const [stem, setStem] = useState(question?.stem ?? '');const [options, setOptions] = useState(question?.options.join('\n') ?? '');const [correct, setCorrect] = useState(Number(question?.solution?.correctOption ?? 0));
  const [answer, setAnswer] = useState(String(question?.solution?.referenceAnswer ?? ''));const [accepted, setAccepted] = useState(((question?.solution?.acceptedAnswers as string[]) ?? []).join('\n'));
  const [explanation, setExplanation] = useState(question?.explanation ?? '');const [source, setSource] = useState(question?.source_evidence ?? '');const [form, setForm] = useState(question?.coverage_form ?? '');const [basis, setBasis] = useState(question?.difficulty_basis ?? '');const [maximum, setMaximum] = useState(question?.maximum ?? 1);const [legacy, setLegacy] = useState(question?.legacy_revision_id ?? '');
  const [rubric, setRubric] = useState<{ id: string; description: string; maximum: number }[]>((question?.rubric as { id: string; description: string; maximum: number }[]) ?? []);
  const [auxiliary, setAuxiliary] = useState<string[]>(question?.auxiliary_points ?? []);
  return <details open={!question} className="bank-review"><summary>{question ? '修订草稿题目' : '新增原创或实质改编题'}</summary><label>用途<select value={purpose} onChange={(e) => setPurpose(e.target.value)}><option value="PRACTICE">考点练习</option><option value="ASSESSMENT">独立检测/模拟卷题</option></select></label>{purpose === 'PRACTICE' && <label>等级<select value={level} onChange={(e) => setLevel(e.target.value as 'simple' | 'middle' | 'hard')}><option>simple</option><option>middle</option><option>hard</option></select></label>}<label>题型<select value={type} onChange={(e) => setType(e.target.value)}>{[['CHOICE', '单项选择'], ['FILL', '填空'], ['CALCULATION', '计算'], ['PROOF', '证明'], ['SHORT', '简答'], ['CODE', '代码'], ['OPERATION', '操作']].map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>题干<textarea value={stem} onChange={(e) => setStem(e.target.value)} /></label>
    {type === 'CHOICE' ? <><label>选项（每项一行）<textarea value={options} onChange={(e) => setOptions(e.target.value)} /></label><label>唯一正确选项<select value={correct} onChange={(e) => setCorrect(Number(e.target.value))}>{options.split('\n').map((o, i) => <option key={i} value={i}>{String.fromCharCode(65 + i)}. {o}</option>)}</select></label></> : <><label>参考答案<textarea value={answer} onChange={(e) => setAnswer(e.target.value)} /></label>{type === 'FILL' && <label>可接受的完整答案（每项一行）<textarea value={accepted} onChange={(e) => setAccepted(e.target.value)} /></label>}</>}
    <label>满分<input type="number" min="0.01" step="0.01" value={maximum} onChange={(e) => setMaximum(Number(e.target.value))} /></label><label>解析与推导<textarea value={explanation} onChange={(e) => setExplanation(e.target.value)} /></label>
    {!['CHOICE', 'FILL'].includes(type) && <div><h4>逐点评分标准</h4>{rubric.map((r, i) => <div key={i} className="row"><input aria-label={`评分点${i + 1}说明`} value={r.description} onChange={(e) => setRubric(rubric.map((x, j) => j === i ? { ...x, description: e.target.value } : x))} /><input aria-label={`评分点${i + 1}分值`} type="number" min="0.01" step="0.01" value={r.maximum} onChange={(e) => setRubric(rubric.map((x, j) => j === i ? { ...x, maximum: Number(e.target.value) } : x))} /></div>)}<Button variant="secondary" onClick={() => setRubric([...rubric, { id: `step${rubric.length + 1}`, description: '', maximum: 1 }])}>添加评分点</Button></div>}
    <label>来源或改编依据<textarea value={source} onChange={(e) => setSource(e.target.value)} /></label><label>重要表现形式<input value={form} onChange={(e) => setForm(e.target.value)} /></label><label>难度依据（middle需真题定位）<textarea value={basis} onChange={(e) => setBasis(e.target.value)} /></label><label>对应旧题版本身份（可选）<input value={legacy} onChange={(e) => setLegacy(e.target.value)} /></label><details><summary>辅助考点（不重复计配额）</summary>{data.points.filter((p) => p.point_key !== point).map((p) => <label key={p.point_key}><input type="checkbox" checked={auxiliary.includes(p.point_key)} onChange={(e) => setAuxiliary(e.target.checked ? [...auxiliary, p.point_key] : auxiliary.filter((x) => x !== p.point_key))} />{p.title}</label>)}</details>
    <Button loading={busy} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/versions/${data.version.id}/questions${question ? `/${question.id}` : ''}`, question ? 'PUT' : 'POST', { pointKey: point, auxiliaryPoints: auxiliary, purpose, level: purpose === 'PRACTICE' ? level : null, type, stem, options: type === 'CHOICE' ? options.split('\n') : [], solution: type === 'CHOICE' ? { correctOption: correct } : { referenceAnswer: answer, ...(type === 'FILL' ? { acceptedAnswers: accepted.split('\n').filter(Boolean) } : {}) }, explanation, rubric: ['CHOICE', 'FILL'].includes(type) ? [] : rubric, maximum, sourceEvidence: source, coverageForm: form, difficultyBasis: basis, legacyRevisionId: legacy || null, expectedRevision: data.version.revision }))}>保存草稿（不会发布）</Button>
  </details>;
}
function Verification({ courseId, data, question, act, busy }: { courseId: string; data: AdminData; question: BankQuestion; act: Action; busy: boolean }) {
  const [solve, setSolve] = useState('');const [check, setCheck] = useState('');const [reason, setReason] = useState('');
  return <div><label>独立重新求解证据<textarea value={solve} onChange={(e) => setSolve(e.target.value)} /></label><label>答案、解析、唯一性、干扰项、范围与难度复核<textarea value={check} onChange={(e) => setCheck(e.target.value)} /></label><Button loading={busy} disabled={data.version.state !== 'DRAFT' || !solve.trim() || !check.trim()} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/questions/${question.id}/verify`, 'POST', { solveEvidence: solve, recheckEvidence: check, expectedRevision: data.version.revision }))}>确认逐题复核</Button><label>删除原因<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><Button variant="secondary" loading={busy} disabled={!reason.trim()} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/questions/${question.id}/retire`, 'POST', { reason }))}>删除不合格题</Button></div>;
}
function PaperEditor({ courseId, data, act, busy, paper }: { courseId: string; data: AdminData; act: Action; busy: boolean; paper?: BankPaper & { questions: BankQuestion[] } }) {
  const [kind, setKind] = useState<string>(paper?.kind ?? 'MOCK');const [chapter, setChapter] = useState(paper?.chapter_id ?? '');const [variant, setVariant] = useState(paper?.variant ?? 'A');const [title, setTitle] = useState(paper?.title ?? '');const [minutes, setMinutes] = useState(paper?.limit_minutes ?? 150);const [source, setSource] = useState(paper?.structure_evidence ?? '');const [selected, setSelected] = useState<string[]>(paper?.questions.map((q) => q.id) ?? []);
  const questions = useQuery({ queryKey: ['admin-bank-paper-candidates', courseId, data.version.id], queryFn: () => bankRequest<(BankQuestion & { purpose: string })[]>(`/admin/bank/courses/${courseId}/questions?versionId=${data.version.id}`) });
  return <details className="bank-review"><summary>{paper ? '修订固定试卷草稿' : '编制独立固定试卷'}</summary><label>用途<select value={kind} onChange={(e) => setKind(e.target.value)}><option value="MOCK">全科模拟卷</option><option value="CHAPTER">章节检测卷</option></select></label>{kind === 'CHAPTER' ? <label>章节<select value={chapter} onChange={(e) => setChapter(e.target.value)}><option value="">请选择</option>{data.chapters.filter((c) => c.required).map((c) => <option key={c.chapter_id} value={c.chapter_id}>{c.title}</option>)}</select></label> : <label>模拟卷版本<select value={variant} onChange={(e) => setVariant(e.target.value)}><option>A</option><option>B</option><option>C</option></select></label>}<label>卷名<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>规定分钟数<input type="number" min="1" value={minutes} onChange={(e) => setMinutes(Number(e.target.value))} /></label><label>结构、分值及真实考试难度依据<textarea value={source} onChange={(e) => setSource(e.target.value)} /></label><p>按下方题目顺序固定试卷；满分、版本、主辅考点覆盖及独立性由后端校验。</p><ol>{selected.map((id, index) => <li key={id}>{questions.data?.find((q) => q.id === id)?.coverage_form ?? id}<Button variant="secondary" disabled={index === 0} onClick={() => { const next = [...selected];[next[index - 1], next[index]] = [next[index], next[index - 1]];setSelected(next); }}>上移第{index + 1}题</Button><Button variant="secondary" disabled={index + 1 === selected.length} onClick={() => { const next = [...selected];[next[index + 1], next[index]] = [next[index], next[index + 1]];setSelected(next); }}>下移第{index + 1}题</Button></li>)}</ol>{questions.data?.filter((q) => q.purpose === 'ASSESSMENT' && q.review_state === 'VERIFIED').map((q) => <label key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, q.id] : selected.filter((s) => s !== q.id))} />{q.type} · {q.maximum}分 · {q.coverage_form}</label>)}<Button loading={busy} disabled={!selected.length || !title.trim() || !source.trim()} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/versions/${data.version.id}/papers${paper ? `/${paper.id}` : ''}`, paper ? 'PUT' : 'POST', { kind, chapterId: kind === 'CHAPTER' ? chapter : null, variant: kind === 'CHAPTER' ? 'CHAPTER' : variant, title, limitMinutes: minutes, structureEvidence: source, questionIds: selected, expectedRevision: data.version.revision }))}>保存固定试卷草稿</Button></details>;
}
function PaperReview({ courseId, data, paper, act, busy }: { courseId: string; data: AdminData; paper: AdminData['papers'][number]; act: Action; busy: boolean }) {
  const [solve, setSolve] = useState('');const [check, setCheck] = useState('');const [open, setOpen] = useState(false);
  const detail = useQuery({ queryKey: ['admin-bank-paper-detail', courseId, paper.id], enabled: open, queryFn: () => bankRequest<BankPaper & { questions: BankQuestion[] }>(`/admin/bank/courses/${courseId}/papers/${paper.id}`) });
  return <details className="bank-review" onToggle={(e) => setOpen(e.currentTarget.open)}><summary>{paper.title} · {paper.reviewed ? '已审核' : '待审核'}</summary>{detail.isPending ? <p>读取试卷题目…</p> : detail.isError ? <p role="alert">{detail.error.message}</p> : <><p>规定 {detail.data.limit_minutes} 分钟 · {detail.data.questions.length} 题 · 满分 {detail.data.questions.reduce((sum, q) => sum + q.maximum, 0)}</p><p>结构依据：{detail.data.structure_evidence}</p>{detail.data.questions.map((q, index) => <article key={q.id}><h4>第{index + 1}题 · {q.type} · {q.maximum}分</h4><MathText text={q.stem} />{q.options.map((o, i) => <p key={i}>{String.fromCharCode(65 + i)}. <MathText text={o} /></p>)}<pre>{JSON.stringify(q.solution, null, 2)}</pre><MathText text={q.explanation ?? ''} /><pre>{JSON.stringify(q.rubric, null, 2)}</pre></article>)}{data.version.state === 'DRAFT' && <PaperEditor key={paper.id + ':' + paper.revision} courseId={courseId} data={data} act={act} busy={busy} paper={detail.data} />}</>}<label>完整重解与分值复核<textarea value={solve} onChange={(e) => setSolve(e.target.value)} /></label><label>结构及难度复核<textarea value={check} onChange={(e) => setCheck(e.target.value)} /></label><Button loading={busy} disabled={!solve || !check || data.version.state !== 'DRAFT'} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/papers/${paper.id}/verify`, 'POST', { solveEvidence: solve, recheckEvidence: check, expectedRevision: data.version.revision }))}>审核固定试卷</Button></details>;
}
function Grade({ item, act, busy }: { item: GradeItem; act: Action; busy: boolean }) {
  const [state, setState] = useState('NEEDS_REVIEW');const [score, setScore] = useState('');const [reason, setReason] = useState('');
  return <article className="bank-review"><MathText text={item.stem} /><p>当前状态：{item.grading_state} · 满分 {item.maximum}</p><h4>学生作答</h4><pre>{JSON.stringify(item.answer, null, 2)}</pre><details><summary>参考答案及逐点评分标准</summary><pre>{JSON.stringify({ solution: item.solution, rubric: item.rubric }, null, 2)}</pre></details><label>处理状态<select value={state} onChange={(e) => setState(e.target.value)}><option value="NEEDS_REVIEW">待核对</option><option value="FAILED">评分失败</option><option value="PENDING">待评分</option><option value="GRADED">人工确认最终分数</option></select></label>{state === 'GRADED' && <label>最终得分<input type="number" min="0" max={item.maximum} step="0.01" value={score} onChange={(e) => setScore(e.target.value)} /></label>}<label>评分依据或失败/待核对原因<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><Button loading={busy} disabled={!reason.trim() || state === 'GRADED' && score === ''} onClick={() => void act(() => bankRequest(item.kind === 'PRACTICE' ? `/admin/bank/attempts/${item.target_id}/grade` : `/admin/bank/sessions/${item.target_id}/answers/${item.question_id}/grade`, 'POST', { state, earned: state === 'GRADED' ? Number(score) : null, reason, expectedRevision: item.revision }))}>保存评分状态</Button></article>;
}

function Qualification({ item, act, busy }: { item: Record<string, unknown>; act: Action; busy: boolean }) {
  const [reason, setReason] = useState('');
  return <article className="bank-review"><p>账号：{String(item.username)} · {String(item.kind)} · {String(item.scope_key)} · 来源 {String(item.source)} · {item.invalidated_at ? '已作废' : '有效'}</p>{!item.invalidated_at && <><label>明确作废依据<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><Button loading={busy} disabled={!reason.trim()} onClick={() => void act(() => bankRequest(`/admin/bank/qualifications/${item.id}/invalidate`, 'POST', { reason }))}>按审核依据作废此凭据</Button></>}</article>;
}

type CleanupItem = { questionId: string; counts?: Record<string, number>; digest?: string; blockedReason?: string };
function HistoryCleanup({ courseId, item, index, act, busy }: { courseId: string; item: CleanupItem; index: number; act: Action; busy: boolean }) {
  const [confirmed, setConfirmed] = useState(false);const [reason, setReason] = useState('');
  const titles: Record<string, string> = { revisions: '题干与答案版本', submissions: '历史作答与快照', sessions: '整份旧检测记录', passes: '关联通过资格', events: '检测作答事件', sessionAnswers: '检测题目与答案', marks: '收藏与疑问标记', positions: '相关学习位置', imports: '旧导入快照', fileLinks: '导入附件关联', replays: '结果重放快照', auditEvents: '该题历史审查快照' };
  return <article className="bank-review"><h3>待清理题目 {index}</h3>{item.blockedReason ? <p role="alert">{item.blockedReason}</p> : <><dl>{Object.entries(item.counts ?? {}).filter(([, count]) => count > 0).map(([key, count]) => <div key={key}><dt>{titles[key] ?? key}</dt><dd>{count} 条</dd></div>)}</dl><label><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />确认删除上述记录和快照，无法恢复</label><label>删除原因<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><Button loading={busy} disabled={!confirmed || !reason.trim()} onClick={() => void act(() => bankRequest(`/admin/bank/courses/${courseId}/questions/${item.questionId}/delete-history`, 'POST', { expectedDigest: item.digest, reason }))}>删除此题及列出的历史</Button></>}</article>;
}

function PracticeBatchPublisher({ courseId, data, act, busy }: { courseId: string; data: AdminData; act: (fn: () => Promise<unknown>) => Promise<void>; busy: boolean }) {
  const [key, setKey] = useState(''); const [ids, setIds] = useState(''); const [evidence, setEvidence] = useState('');
  const questionIds = ids.split(/[,\s]+/).filter(Boolean);
  return <details><summary>分批发布合格练习（每批最多100道）</summary><p>按考点、等级的完整10题组发布。只开放练习，不开放章节检测或模拟卷。待核实题、重复题、缺少求解复核或范围证据的题不能发布。</p><label>批次标识<input value={key} onChange={(e) => setKey(e.target.value)} /></label><label>题目身份（每行一个）<textarea rows={5} value={ids} onChange={(e) => setIds(e.target.value)} /></label><label>本批复核依据<textarea value={evidence} onChange={(e) => setEvidence(e.target.value)} /></label><Button disabled={busy || !key.trim() || !evidence.trim() || !questionIds.length || questionIds.length > 100} onClick={() => act(() => bankRequest(`/admin/bank/courses/${courseId}/versions/${data.version.id}/practice-batches`, 'POST', { batchKey: key, evidence, questionIds, expectedRevision: data.version.revision }))}>发布本批合格练习</Button></details>;
}
