import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { bankRequest, type BankQuestion, type BankChapter, type BankPoint, type Level } from '../../api/bank';
import { Button } from '../../components/Button';
import { Card } from '../../components/Card';
import { MathText } from '../../components/MathText';
import { UnsavedGuard } from '../../components/UnsavedGuard';
import { AnswerInput } from './BankPractice';
type Answer = { text?: string; selectedOption?: number };
type Question = BankQuestion & { answer: Answer; files: { id: string; name: string; mimeType: string }[] };
interface Batch { id: string; revision: number; questions: Question[]; state: string; taskId: string | null; error?: string; workerOnline: boolean; workerReason: string; result?: { reviewItems: string[]; answers: { number: string; recognizedAnswer: string; pages: number[]; reviewItems: string[]; points: { pointId: string; score: number; reason: string }[] }[] } }
export const hasBatchAnswer = (q: Question, answer: Answer = q.answer) => q.type === 'CHOICE' ? answer.selectedOption !== undefined : Boolean(answer.text?.trim() || q.files.length);
const states: Record<string, string> = { QUEUED: '已申请，等待批改', GRADING: '正在批改', REVIEW: '批改结果需要管理员核对', COMPLETED: '批改完成', FAILED: '批改失败' };
export function PointPracticeBatch({ courseId, chapter, point, level }: { courseId: string; chapter: BankChapter; point: BankPoint; level: Level }) {
 const client = useQueryClient(); const [batch, setBatch] = useState<Batch | null>(null); const [index, setIndex] = useState(0); const [value, setValue] = useState<Answer>({}); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [preview, setPreview] = useState('');
 async function open(newAttempt = false) {const b = await bankRequest<Batch>(`/bank/courses/${courseId}/practice-batches`, 'POST', { chapterId: chapter.chapter_id, pointKey: point.point_key, level, newAttempt });setBatch(b);setIndex(0);setValue(b.questions[0].answer);setDirty(false);setPreview('');}
 useEffect(() => {let active = true;bankRequest<Batch>(`/bank/courses/${courseId}/practice-batches`, 'POST', { chapterId: chapter.chapter_id, pointKey: point.point_key, level, newAttempt: false }).then(b => {if (active) {setBatch(b);setValue(b.questions[0].answer);}}).catch(e => {if (active) setError(e.message);});return () => {active = false;};}, [courseId, chapter.chapter_id, point.point_key, level]);
 useEffect(() => {if (!batch?.taskId || !['QUEUED', 'GRADING'].includes(batch.state)) return;let active = true;const timer = setInterval(() => {void bankRequest<Batch>(`/bank/practice-batches/${batch.id}`).then(b => {if (active) {setBatch(b);if (['COMPLETED', 'REVIEW'].includes(b.state)) void client.invalidateQueries({ queryKey: ['bank-overview', courseId] });}}).catch(e => {if (active) setError(e.message);});}, 5000);return () => {active = false;clearInterval(timer);};}, [batch?.id, batch?.taskId, batch?.state, client, courseId]);
 useEffect(() => {if (!dirty) return;const warn = (e: BeforeUnloadEvent) => {e.preventDefault();};window.addEventListener('beforeunload', warn);return () => window.removeEventListener('beforeunload', warn);}, [dirty]);
 async function act(work: () => Promise<void>) {setBusy(true);setError('');try {await work();} catch (e) {setError(e instanceof Error ? e.message : '操作失败');} finally {setBusy(false);}}
 async function save(): Promise<Batch> {if (!batch) throw Error('练习尚未读取');if (!dirty) return batch;const b = await bankRequest<Batch>(`/bank/practice-batches/${batch.id}/answers/${batch.questions[index].id}`, 'PUT', { answer: value, expectedRevision: batch.revision });setBatch(b);setDirty(false);return b;}
 if (!batch) return <Card><p role={error ? 'alert' : 'status'}>{error || '正在读取整组练习…'}</p>{error && <Button onClick={() => void act(() => open())}>重试</Button>}</Card>;
 const q = batch.questions[index]; const locked = batch.state !== 'DRAFT'; const completed = batch.questions.filter((item, i) => hasBatchAnswer(item, i === index ? value : item.answer)).length;
 return <Card className="bank-practice"><UnsavedGuard dirty={dirty} /><h3>{point.title} · {level === 'simple' ? '基础练习' : level === 'middle' ? '考试水平练习' : '提高练习'}</h3><p>第 {index + 1} / 10 题 · 已作答 {completed}/10</p><p className="secondary">文字和作答图片均可保存。完成10题后统一申请批改；图片每题最多2张，支持JPG、PNG，每张不超过8MB。</p>
 <div className="row" aria-label="选择题号">{batch.questions.map((item, i) => <Button key={item.id} variant={i === index ? 'primary' : 'secondary'} disabled={busy} onClick={() => void act(async () => {const b = await save();setIndex(i);setValue(b.questions[i].answer);setPreview('');})}>{i + 1}{hasBatchAnswer(item, i === index ? value : item.answer) ? ' ✓' : ''}</Button>)}</div>
 <MathText text={q.stem} /><AnswerInput question={q} value={value} disabled={busy || locked} onChange={v => {setValue(v);setDirty(true);}} />
 {q.type !== 'CHOICE' && <div className="bank-images"><label>上传本题作答图片<input aria-label="上传本题作答图片" type="file" accept="image/jpeg,image/png" disabled={busy || locked || q.files.length >= 2} onChange={e => {const f = e.target.files?.[0];e.target.value = '';if (!f) return;if (!['image/jpeg', 'image/png'].includes(f.type) || f.size > 8 * 1024 * 1024) {setError('请选择不超过8MB的JPG或PNG图片');return;}void act(async () => {const b = await save();const form = new FormData();form.append('file', f);form.append('expectedRevision', String(b.revision));setBatch(await bankRequest<Batch>(`/bank/practice-batches/${b.id}/answers/${q.id}/pages`, 'POST', form));});}} /></label>{q.files.map(f => <div className="row" key={f.id}><span>{f.name}</span><Button variant="secondary" disabled={busy} onClick={() => void act(async () => {const image = await bankRequest<{ mimeType: string; contentBase64: string }>(`/bank/practice-batches/${batch.id}/pages/${f.id}`);setPreview(`data:${image.mimeType};base64,${image.contentBase64}`);})}>查看图片</Button>{!locked && <Button variant="secondary" disabled={busy} onClick={() => void act(async () => {const b = await save();setBatch(await bankRequest<Batch>(`/bank/practice-batches/${b.id}/answers/${q.id}/pages/${f.id}?expectedRevision=${b.revision}`, 'DELETE'));setPreview('');})}>移除</Button>}</div>)}{preview && <img src={preview} alt="本题作答图片" style={{ maxWidth: '100%', maxHeight: 500 }} />}</div>}
 {!locked && <div className="row"><Button variant="secondary" loading={busy} onClick={() => void act(async () => {await save();})}>保存本题</Button><Button loading={busy} disabled={completed !== 10} onClick={() => void act(async () => {const b = await save();setBatch(await bankRequest<Batch>(`/bank/practice-batches/${b.id}/grading`, 'POST', { expectedRevision: b.revision }));})}>完成10题，申请批改</Button></div>}
 {locked && <div role="status"><strong>{states[batch.state] || batch.state}</strong>{['QUEUED', 'GRADING'].includes(batch.state) && !batch.workerOnline && <p>{batch.workerReason}</p>}{batch.error && <p>{batch.error}</p>}{batch.result && <><p>{batch.result.reviewItems.join('；')}</p>{batch.result.answers.map(a => <details key={a.number} open={Number(a.number) === index + 1}><summary>第{a.number}题 · {batch.state === 'REVIEW' ? '待核对分数' : '得分'} {a.points.reduce((sum, p) => sum + p.score, 0)} / {batch.questions[Number(a.number) - 1].maximum}</summary><MathText text={a.recognizedAnswer} />{a.points.map(p => <p key={p.pointId}>{p.score}分 · {p.reason || '该评分点通过'}</p>)}{a.reviewItems.length > 0 && <p role="alert">{a.reviewItems.join('；')}</p>}</details>)}</>}{['COMPLETED', 'FAILED', 'REVIEW'].includes(batch.state) && <Button variant="secondary" disabled={busy} onClick={() => void act(() => open(true))}>开始新一组练习</Button>}</div>}
 {error && <p role="alert">{error}</p>}{dirty && <p role="status">有未保存的作答，切换题号时会自动保存。</p>}
 </Card>;
}
